### ISSUE TITLE
Add Usage Documentation

### ISSUE THREAD

**Issue by siddharth-tewari** [eXhumer/pyeXF1LT#2]
Hello, how to use this program? Any method?

**Comment by eXhumer** [comment]
This package can be used as a library or as a standalone program. Upon installation of the package in a Python environment, you can access `eXF1LT` executable stub from your Python environment. Usage help for the executable can be viewed with `eXF1LT --help`. By default, you will only be able to access the `message-logger` action only. If you want to access Discord bot action, you will need to install [pyeXDC](https://github.com/eXhumer/pyeXDC) package as well. There is no help section on documentation currently as I am changing the interface to access regularly.

**Comment by siddharth-tewari** [comment]
![image](https://user-images.githubusercontent.com/76590952/176612692-b14e7f4f-5007-411d-9fa7-34925a91c62a.png)
Hello, I am getting the following issue. How to fix it?

**Comment by eXhumer** [comment]
The union type was introduced in Python 3.10 via [PEP 604](https://peps.python.org/pep-0604/). I will update the code to fix it for 3.9 soon.

**Comment by eXhumer** [comment]
Make sure to re-install the package after pulling the repository with latest changes.

**Comment by siddharth-tewari** [comment]
Ok, thank you

**Comment by siddharth-tewari** [comment]
![image](https://user-images.githubusercontent.com/76590952/176664609-f54849be-a20f-417d-bbf0-e64a0c0c92e3.png)
Is this what should I be getting?

**Comment by eXhumer** [comment]
`eXF1LT --help`

**Comment by siddharth-tewari** [comment]
OK
